### ISSUE TITLE
Compile instead of embed

### ISSUE THREAD

**Issue by iusearch** [jm33-m0/emp3r0r#144]
It would be great if those statically compiled binary in the repo can be actually "compiled" instead of just being there. Or at least take bins from a trusted distributor like arch repo or smth. Btw, is your siscon "妹控" or "姐控"?

**Comment by jm33-m0** [comment]
All static binaries are generated using `staticx` or their own build scripts under Alpine Linux, it should be easy to reproduce. If you were interested you can write some scripts to automate the build process.

> Or at least take bins from a trusted distributor like arch repo or smth
Unfortunately this is impossible since none of the distros distribute static binaries, not even Alpine

> is your siscon "妹控" or "姐控"?
It's "姐控"
