### ISSUE TITLE
.exe? for linux

### ISSUE THREAD

**Issue by JackDev-cc** [jm33-m0/emp3r0r#152]
Building agent on linux, selecting linux and the output is a .exe?

**Comment by jm33-m0** [comment]
What's wrong with that?

**Comment by JackDev-cc** [comment]
Fair enough, my bad on that but even with renaming running on MacOS or Ubuntu leads to this;
<img width="423" alt="Screenshot 2022-08-06 at 18 41 47" src="https://user-images.githubusercontent.com/51898206/183258120-af648948-65bc-4875-b0b5-384e579a3f7a.png">

**Comment by jm33-m0** [comment]
In case someone has the same question, I am adding an explanation. First of all, `.exe` or dot anything is just file name extension and don't mean a damn thing, they exist just to give people (or some programs) a hint of what type of file they represent. You can name a PE executable file as `foo.exe` or `foo.bar`, the PE format remains intact and can be parsed by any working PE parsers. Second, I use `.exe` because I included `.exe` in `.gitignore` to ignore binary file changes.

**Comment by jm33-m0** [comment]
Windows teaches its users too well about file name extensions, now they think the names actually mean something, while in fact they don't.
