### ISSUE TITLE
Network Scanning Idea

### ISSUE THREAD

**Issue by zero77** [jm33-m0/emp3r0r#16]
Hopefully this could save you development time, if not don't worry about this idea.

In your future releases list you have network scanning, instead of building and maintaining a scanner. 
You could use [bettercap](https://github.com/bettercap/bettercap) as it can do active and passive scanning as well as other things.

You could drop the binary to memory and get it to do all the work and manage it via commands.

**Comment by jm33-m0** [comment]
That's an interesting idea, I will definitely try it out.
One problem though, if we want to include bettercap, we will have to include libpcap as well.

Currently I don't know if we can make it portable, but it's worth trying.

Also, it can be added to https://github.com/jm33-m0/static-bins, and used as an independent tool (since it has its own user interface)

**Comment by jm33-m0** [comment]
`bettercap` has been packed with all dependencies (musl libc) and uploaded to https://github.com/jm33-m0/static-bins/tree/main/vaccine
