### ISSUE TITLE
Windows ConPTY issues

### ISSUE THREAD

**Issue by opensesamedoors** [jm33-m0/emp3r0r#201]
![Screenshot from 2023-04-17 05-59-12](https://user-images.githubusercontent.com/7597988/232353245-7e47d49b-8f6a-4687-b8f0-ce68fbb223e4.png)

**Comment by jm33-m0** [comment]
You reported this in #199, is this still an issue in the latest release?

**Comment by jm33-m0** [comment]
`/dev/shm/` is no longer used since [this commit](https://github.com/jm33-m0/emp3r0r/commit/c090e0854e4ccfeb462728e54dd1ef73e186ad50#diff-d6dd2ed8a2e2c30a6e5c5283101ff023bd575b3a21cb89f9c43a2e299164f628L30).

https://github.com/jm33-m0/emp3r0r/blob/6f838fc270978b003f8d6c9aaa93fea74ec40ced/core/lib/agent/sshd_linux.go#L44

According to your screenshot you are not using the latest version. Can you try with the latest version and see if it works? I did a quick test and no bugs were found.

> Which IDE do you use to debug the tmux GUI,now I just use function PRINTF

I don't use an IDE, I'm a vim user. And I believe this bug is already fixed, the root cause of this issue is the self deletion feature and it has been addressed.

**Comment by jm33-m0** [comment]
I can confirm this for Windows platform, thanks for reporting. I will push a fix soon.

**Comment by jm33-m0** [comment]
Further testing shows that `conhost.exe` is missing for **32 bit** agent, if you build it with `amd64` option it will pop up shell just fine.

And currently ConPTY buffer size can't be auto resized correctly, the shell is barely usable.

**Comment by jm33-m0** [comment]
Thanks, I will try to implement this solution in future releases.

**Comment by jm33-m0** [comment]
- [ ] Fix shell for 32bit Windows program
- [ ] Fix auto-resizing for Windows ConPTY shell

Matching the console buffer size between C2 and agent side is quite tricky for Windows. There's a `mode.com` utility that works like `stty` under Linux, but running it can only change the console buffer of the calling process, and the shell process is a child process thus unaffected.

The ideal way is to execute `mode /con:cols=x lines=y` command in the shell in real time. Currently the solution I can think of is to implement a go routine that runs in background (along with the `elvsh` shell, so they live in the same process) and reads buffer size from a environment variable (`WIDTH=x`) then resizes its console buffer (with `mode.com` or `term` package from Go).
