### ISSUE TITLE
`elvsh` unable to start, agent binary deleted

### ISSUE THREAD

**Issue by winezer0** [jm33-m0/emp3r0r#246]
# Describe the bug

ssh is unavailable when you select a client

![image](https://github.com/jm33-m0/emp3r0r/assets/46115146/5f559839-6154-44ac-bf9f-7ea6a93b4d7e)

The server environment is kali
![image](https://github.com/jm33-m0/emp3r0r/assets/46115146/25b5933a-24f6-43af-a799-9179737064ec)

**Comment by jm33-m0** [comment]
It looks like the agent binary got deleted. Since `elvsh` shell requires agent binary to be present, it won't be able to start, thus no ssh shell available. Please check if this happens on other machines as well, if yes, there will be a bug to fix.

You can always `use interactive_shell` and `set shell bash` to open a system shell.

**Comment by winezer0** [comment]
On version 1.31.4, I tried to run the agent on liunx. After running, the agent will be automatically deleted, including kali 2022 and centos 7.6。

I mistakenly thought it was your latest feature

**Comment by jm33-m0** [comment]
> After running, the agent will be automatically deleted,

This is expected and intentional. If you don't want it to self-delete, you can set `PERSISTENCE=true` when running the agent binary.
